### ISSUE TITLE
Row example?

### ISSUE THREAD

**Issue by lukepighetti** [sushmoyr/animated_multichild#1]
Hi there, I'm unable to get this to work. Can you show an example of a working AnimatedRow? My expectation here was to be able to change the children and have it automatically animate. I am testing this by hot reloading while changing the seed list

```dart
  @override
  Widget build(BuildContext context) {
    return AnimatedRow(
      children: [
        for (final p in [1, 2, 3])
          // for (final p in [1, 2, 3, 4])
          SizedBox.square(
            key: ValueKey(p),
            dimension: 80,
            child: Placeholder(
              child: Text(
                '$p',
              ),
            ),
          ),
      ],
    );
  }
```

**Comment by Juliotati** [comment]
@lukepighetti I guess you need to use `transitionBuilder` that returns the animation you want?

**Comment by lukepighetti** [comment]
It looks like this package only works for presenting an entire row, not modifying it?

**Comment by Juliotati** [comment]
@lukepighetti i just tried your exact example and it works fine 👀 

> i'm pressing hot restart in the video

https://github.com/sushmoyr/animated_multichild/assets/59662912/86c354fb-ea6d-40a4-874b-b8c6210c9da4

**Comment by sushmoyr** [comment]
You need a hot restart to see the changed effects. Because, the animation runs only when the widget is created for the first time. This is to avoid unnecessary animations when the widgets are loading lazily.

**Comment by lukepighetti** [comment]
OIC. I thought this was animating adding/removing items in the Row. Do you know of any way to do this?
